name = "cf-chat"
main = "src/worker.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[site]
bucket = "./dist"

[vars]
JWT_SECRET = "A6u4cNwq9xW3yP0rGmT8VbJsKfQ2ZdEhL1tR5oU7pYcI0nH3sF"
SMTP_HOST = "email-smtp.us-east-1.amazonaws.com"
SMTP_PORT = "25"
SMTP_USER = "AKIA2HZN54SYRD7HIEEL"
SMTP_PASS = "BKiBIXdwgUYyb7OoOF7UcVBvI99WLYeYR61bxsI2cyol"
SMTP_FROM = "noreply@serverhelper.xyz"
APP_URL = "cf-chat.serverhelper.workers.dev"

[[d1_databases]]
binding = "DB"
database_name = "cf-chat-db"
database_id = "86dbb872-2cfa-4087-8b1d-5fc06f06e919"

[[r2_buckets]]
binding = "R2"
bucket_name = "cf-chat-files"

[[kv_namespaces]]
binding = "KV"
id = "f088d2b8d83c4353a85ba95dea6abb0e"

[ai]
binding = "AI"

[[durable_objects.bindings]]
name = "CHAT_ROOM"
class_name = "ChatRoom"

[[migrations]]
tag = "v1"
new_classes = ["ChatRoom"]

[build]
command = "npm run build:web"

[dev]
port = 8787
local_protocol = "http"

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1